name: Run Scripts and Commit Changes

on:
  workflow_dispatch:  # This event allows manual triggering

env:
  AQICN_TOKEN: '${{ secrets.AQICN_TOKEN }}'
  UNSPLASH_ACCESS_KEY: '${{ secrets.UNSPLASH_ACCESS_KEY }}'

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify the Python version you need

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # If you have a requirements file
      - name: Check Tables
        run: python src/check_sqlite_connection.py

      - name: Run get_aqi.py
        run: python src/get_aqi.py

      - name: Run insert_to_aqicn_staging.py
        run: python src/insert_to_aqicn_staging.py

      - name: Run insert_to_aqicn.py
        run: python src/insert_to_aqicn.py

      - name: Run insert_into_station_dim.py
        run: python src/insert_into_station_dim.py

      - name: Run insert_into_city_dim.py
        run: python src/insert_into_city_dim.py

      - name: Run generate_city_images.py
        run: python src/generate_city_images.py

      - name: Run export_to_json_priority.py
        run: python src/export_to_json_priority.py

      - name: Run export_to_json.py
        run: python src/export_to_json.py
      - uses: stefanzweifel/git-auto-commit-action@v4
