name: Run Scripts and Commit Changes

on:
  workflow_dispatch:  # This event allows manual triggering

env:
  AQICN_TOKEN: '${{ secrets.AQICN_TOKEN }}'
  UNSPLASH_ACCESS_KEY: '${{ secrets.UNSPLASH_ACCESS_KEY }}'
  ENCRYPT_KEY: '${{ secrets.ENCRYPT_KEY }}'

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify the Python version you need

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # If you have a requirements file

      - name: Decrypt large secret
        run: ./src/bash/decrypt.sh
        env:
            ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
          
      - name: aqicn_staging load
        run: python src/python/aqi_staging.py

      - name: aqicn load
        run: python src/python/aqi.py

      - name: station_dim load
        run: python src/python/station_dim.py

      - name: city_dim load
        run: python src/python/city_dim.py

      - name: export atta.json
        run: python src/atta.py

      - name: export atta_priority.json
        run: python src/python/atta_priority.py

      - uses: stefanzweifel/git-auto-commit-action@v4
